"""AI Integration — real implementation for Phase 1.

This service calls the Groq API to act as a BRD consultant.
It receives chat history and the current draft state, and returns a structured
response containing both the agent's chat reply and any draft field updates.
"""

import json
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession
from groq import AsyncGroq

from app.config import settings
from app.repositories import answer_repository, bubble_repository, section_repository


class DraftUpdate(BaseModel):
    section_id: str = Field(..., description="The 'section_id' of the BRD field to update")
    draft_content: str = Field(..., description="Formal draft content generated by AI based on conversation")
    confidence_score: int = Field(..., description="Completeness score (0-100)")


class AIResponse(BaseModel):
    agent_message: str = Field(..., description="The chat reply to the user")
    draft_updates: list[DraftUpdate] = Field(
        default_factory=list, 
        description="List of BRD fields updated. Only include fields that have meaningful new information."
    )


SYSTEM_PROMPT = """You are an expert Business Analyst acting as a BRD (Business Requirement Document) Consultant.
Your task is to guide the user to complete a 26-field Business Requirement Document through a conversational interface.

# CORE RULES
1. ONLY discuss topics related to the BRD creation.
2. Ask ONE specific, clear follow-up question at a time if information is incomplete. Do not overwhelm the user.
3. Extract any definitive answers from the user into formal, professional business language for the "draft_content".
4. Evaluate completeness ("confidence_score"):
   - 0-30: Vague or barely relevant information. Ask follow up.
   - 40-70: Good start, but missing key details (e.g., metrics, target audience). Ask follow up.
   - 80-100: Comprehensive and actionable. Acknowledge and move on to the next gap.

# CURRENT STATE
- User's active room: {current_room_title}
- Current Draft Status: 
{current_draft_summary_json}

# RECENT CHAT HISTORY
{history_context}

# OBJECTIVE
Based on the latest user message, respond with a JSON object matching the exact schema. 
- 'agent_message' is your natural conversational response.
- 'draft_updates' MUST be a JSON array (list), even if empty. If there are no updates, return `[]`.

Example Output:
{{
  "agent_message": "Got it. Who is the primary target audience for this feature?",
  "draft_updates": [
    {{
      "section_id": "business_goal",
      "draft_content": "The main business goal is to increase user retention by 20% in Q3.",
      "confidence_score": 85
    }}
  ]
}}
"""


async def get_reply(
    session: AsyncSession,
    *,
    conversation_id: str,
    room_title: str,
    message_text: str
) -> AIResponse:
    if not settings.groq_api_key:
        return AIResponse(
            agent_message="Got it — logged. What else can you tell me about this? (Dummy AI: Please set GROQ_API_KEY in .env)",
            draft_updates=[]
        )

    # 1. Fetch Chat History (last 15 messages for good context)
    bubbles = await bubble_repository.list_by_conversation(session, conversation_id)
    recent_bubbles = bubbles[-15:]
    history_context = "\n".join([f"{b.role.upper()}: {b.text}" for b in recent_bubbles])

    # 2. Fetch Current Draft Status
    sections = await section_repository.list_by_conversation(session, conversation_id)
    answers = await answer_repository.list_by_conversation(session, conversation_id)

    section_dict = {s.section_id: s for s in sections}
    draft_summary = []
    
    # Only include non-general sections
    for a in answers:
        sec = section_dict.get(a.section_id)
        if sec and not sec.is_general:
            draft_summary.append({
                "section_id": sec.section_id,
                "title": sec.title,
                "status": a.status,
                "completeness": a.completeness,
                "confidence": a.confidence,
                "content_preview": a.answer_text[:150] + "..." if a.answer_text else None
            })

    draft_summary_json = json.dumps(draft_summary, indent=2)

    # 3. Prepare Prompt
    system_instruction = SYSTEM_PROMPT.format(
        current_room_title=room_title,
        current_draft_summary_json=draft_summary_json,
        history_context=history_context
    )

    # 4. Call Groq Model
    client = AsyncGroq(api_key=settings.groq_api_key)
    
    try:
        chat_completion = await client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": system_instruction,
                },
                {
                    "role": "user",
                    "content": message_text,
                }
            ],
            model="llama-3.3-70b-versatile",
            response_format={"type": "json_object"},
            temperature=0.7,
        )
        
        response_text = chat_completion.choices[0].message.content
        
        # Sanitize: Some LLMs hallucinate {} instead of [] for empty arrays
        raw_data = json.loads(response_text)
        if "draft_updates" in raw_data and isinstance(raw_data["draft_updates"], dict):
            if not raw_data["draft_updates"]:
                raw_data["draft_updates"] = []
            else:
                raw_data["draft_updates"] = [raw_data["draft_updates"]]
                
        result = AIResponse.model_validate(raw_data)
        return result
        
    except Exception as e:
        print(f"AI Generation Error: {e}")
        return AIResponse(
            agent_message="I'm sorry, I encountered an internal error while processing that.",
            draft_updates=[]
        )
