"""add conversation focused_section_id

Revision ID: e35c6ef172c6
Revises: ed6ab6667259
Create Date: 2026-08-07 12:23:16.071300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35c6ef172c6'
down_revision: Union[str, Sequence[str], None] = 'ed6ab6667259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('focused_section_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'sections', ['focused_section_id'], ['section_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'focused_section_id')
    # ### end Alembic commands ###
