"""init schema

Revision ID: ed6ab6667259
Revises: 
Create Date: 2026-08-07 12:19:41.413272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6ab6667259'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_generated_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('sections',
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('template_key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_sections_conversation_id'), 'sections', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sections_parent_id'), 'sections', ['parent_id'], unique=False)
    op.create_table('answers',
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completeness', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('missing_items', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('bubbles',
    sa.Column('bubble_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bubble_id')
    )
    op.create_index(op.f('ix_bubbles_section_id'), 'bubbles', ['section_id'], unique=False)
    op.create_table('section_dependencies',
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('depends_on_section_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', 'depends_on_section_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_dependencies')
    op.drop_index(op.f('ix_bubbles_section_id'), table_name='bubbles')
    op.drop_table('bubbles')
    op.drop_table('answers')
    op.drop_index(op.f('ix_sections_parent_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_conversation_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
